name: 'Internet-Draft CI'
description: 'Tool for building Internet-Drafts as GitHub Actions'
author: 'Martin Thomson <mt@lowentropy.net>'

inputs:
  make:
    description: 'The make target to build'
    required: false
    default: 'latest'

runs:
  using: 'docker'
  image: 'action/Dockerfile'
  pre: '/usr/bin/make'
  pre-if: "inputs.make != 'latest'"
  args:
    - ${{ inputs.make }}

branding:
  icon: 'check-square'
  color: 'green'
