version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6

      - run:
          name: "Build Docker Image"
          command: |
            if ! git show --name-only --format='' HEAD | grep -q '^\(docker\|.circleci\)/'; then
              exit
            fi
            if [ -n "$CIRCLE_TAG" ]; then
              tag="$CIRCLE_TAG"
            elif [ "$CIRCLE_BRANCH" = "main" ]; then
              tag=latest
            else
              tag="$CIRCLE_BRANCH"
            fi
            docker build -t martinthomson/i-d-template:"$tag" docker/circleci

      - run:
          name: "Run Tests"
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              exit
            fi
            if ! git show --name-only --format='' HEAD | grep -q '^\(docker\|.circleci\)/'; then
              tag=latest
            elif [ "$CIRCLE_BRANCH" = "main" ]; then
              tag=latest
            else
              tag="$CIRCLE_BRANCH"
            fi
            pwd
            ls
            mkdir -p /tmp/artifacts && chmod 777 /tmp/artifacts
            docker run -d --name test \
              --mount type=bind,source=$(pwd),destination=/test \
              --mount type=bind,source=/tmp/artifacts,destination=/tmp/artifacts \
              -w /test martinthomson/i-d-template:"$tag" sleep 30
            docker exec test pip install --user behave black
            docker exec test /home/idci/.local/bin/black --check .
            docker exec test /home/idci/.local/bin/behave --junit --junit-directory /tmp/artifacts tests
            docker rm -f test

      - run:
          name: "Push Docker Image"
          command: |
            if ! git show --name-only --format='' HEAD | grep -q '^\(docker\|.circleci\)/'; then
              exit
            fi
            if [ -n "$CIRCLE_TAG" ]; then
              tag="$CIRCLE_TAG"
            elif [ "$CIRCLE_BRANCH" = "main" ]; then
              tag=latest
            else
              exit
            fi
            if [ -n "$DOCKER_PASSWORD" ]; then
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker push martinthomson/i-d-template:"$tag"
            fi

      - store_artifacts:
          path: /tmp/artifacts

      - store_test_results:
          path: /tmp/artifacts


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*?/
