version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6

      - run:
          name: "Check Formatting"
          command: |
            pip install --user black
            PATH="$PATH:~/.local/bin"
            black --check .

      - run:
          name: "Build Docker Image"
          command: |
            if ! git show --name-only --format='' HEAD | grep -q '^\(docker\|.circleci\)/'; then
              exit
            fi
            if [ -n "$CIRCLE_TAG" ]; then
              tag="$CIRCLE_TAG"
            elif [ "$CIRCLE_BRANCH" = "main" ]; then
              tag=latest
            else
              tag="$CIRCLE_BRANCH"
            fi
            docker build -t martinthomson/i-d-template:"$tag" docker/circleci

      - run:
          name: "Run Tests"
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              exit
            fi
            if ! git show --name-only --format='' HEAD | grep -q '^\(docker\|.circleci\)/'; then
              tag=latest
            elif [ "$CIRCLE_BRANCH" = "main" ]; then
              tag=latest
            else
              tag="$CIRCLE_BRANCH"
            fi
            mkdir -p /tmp/artifacts
            docker run -d --name test -v .:/test -v /tmp/artifacts -w /test martinthomson/i-d-template:"$tag" /bin/true
            docker exec test pip install --user behave
            docker exec test behave --junit --junit-directory /tmp/artifacts tests/*.feature
            docker rm -f test

      - run:
          name: "Push Docker Image"
          command: |
            if ! git show --name-only --format='' HEAD | grep -q '^\(docker\|.circleci\)/'; then
              exit
            fi
            if [ -n "$CIRCLE_TAG" ]; then
              tag="$CIRCLE_TAG"
            elif [ "$CIRCLE_BRANCH" = "main" ]; then
              tag=latest
            else
              exit
            fi
            if [ -n "$DOCKER_PASSWORD" ]; then
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker push martinthomson/i-d-template:"$tag"
            fi

      - store_artifacts:
          path: /tmp/artifacts

      - store_test_results:
          path: /tmp/artifacts


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*?/
