version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6

      - run:
          name: "Check Formatting"
          command: |
            pip3 install --user black
            PATH="$PATH:~/.local/bin"
            black --check .

      - run:
          name: "Run Tests"
          command: |
            if [ -z "$CIRCLE_TAG" ]; then
              pip3 install --user behave
              PATH="$PATH:~/.local/bin"
              mkdir -p /tmp/artifacts
              behave --junit --junit-directory /tmp/artifacts tests/*.feature
            fi

      - run:
          name: "Build and Push Docker Image"
          command: |
            if ! git show --name-only --format='' HEAD | diff -q '^\(docker\|.circleci\)/'; then
              exit
            fi
            if [ -n "$CIRCLE_TAG" ]; then
              tag="$CIRCLE_TAG"
              push=y
            elif [ "$CIRCLE_BRANCH" = "main" ]; then
              tag=latest
              push=y
            else
              tag="$CIRCLE_BRANCH"
              push=n
            fi
            docker build -t martinthomson/i-d-template:"$tag" docker/circleci
            if [ "$push" = y -a -n "$DOCKER_PASSWORD" ]; then
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker push martinthomson/i-d-template:"$tag"
            fi

      - store_artifacts:
          path: /tmp/artifacts

      - store_test_results:
          path: /tmp/artifacts


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*?/
