name: "Update Docker Image for GitHub Action"

on:
  push:
    paths:
    - "docker/**"
    - ".github/workflows/docker.yml"
  schedule:
    # Once monthly at a randomly selected time.
    - cron: "24 2 3,18 * *"

jobs:
  build:
    name: "Update Docker Image"
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Get Tag"
      id: tag
      run: |
        ref="${{ github.ref }}"
        label="latest"
        if [ "$ref" = "refs/heads/main" ]; then
          test=false
        elif [ "${ref#refs/tags/}" != "$ref" ]; then
          label="${ref#refs/tags/}"
          test=false
        else
          test=true
        fi
        tag() {
          echo "${1}martinthomson/i-d-template${2}:${label}"
        }
        if "$test"; then
          action_tags="$(tag localhost:5000/ -action)"
          circle_tags="$(tag localhost:5000/ "")"
        else
          action_tags="$(tag "" -action),$(tag ghcr.io/ -action)"
          circle_tags="$(tag "" ""),$(tag ghcr.io/ "")"
        fi
        echo "::set-output name=label::$label"
        echo "::set-output name=action_tags::$action_tags"
        echo "::set-output name=action_tags::$circle_tags"

    - name: "Setup Docker Buildx"
      uses: docker/setup-buildx-action@v1

    - name: "Login to DockerHub"
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: "Login to GitHub Container Registry"
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PASSWORD }}

    - name: "Build and Publish GitHub Actions Image"
      uses: docker/build-push-action@v2
      with:
        context: ./docker/action
        file: ./docker/action/Dockerfile
        push: true
        load: true
        tags: ${{ steps.tag.outputs.action_tags }}

    - name: "Build and Publish CircleCI Image"
      uses: docker/build-push-action@v2
      with:
        context: ./docker/circleci
        file: ./docker/circleci/Dockerfile
        build-args: |
          VERSION=${{ steps.tag.outputs.label }}
        push: true
        tags: ${{ steps.tag.outputs.circle_tags }}
