name: "Validate Workflows in Template"

on:
  workflow_dispatch:
  push:
    paths:
    - "template/.github/workflows/**"

jobs:
  build:
    name: "Validate Workflows"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Compare"
      run: |
        set +e
        git clone https://github.com/martinthomson/internet-draft-template idt
        e=''
        for src in template/.github/workflows/*.yml; do
          dst="idt/${i#*/}"
          [ -f "$dst" ] || e="$e\n$dst is missing"
          diff -u "$dst" "$src" || e="$e\n$dst is different"
        done
        if [ -n "$e" ]; then
          printf "$e"
          exit 1
        fi
